version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/typescript-estree"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: stylelint
    versions:
    - 13.12.0
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.13.0
    - 7.13.8
  - dependency-name: react-hook-form
    versions:
    - 6.14.2
    - 6.15.0
    - 6.15.1
    - 6.15.3
    - 6.15.4
  - dependency-name: "@babel/plugin-transform-typescript"
    versions:
    - 7.12.1
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: next
    versions:
    - 9.5.4
  - dependency-name: acorn
    versions:
    - 6.4.2
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.13.0
